//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cooler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bag_Types
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bag_Types()
        {
            this.Bag_Replacement = new HashSet<Bag_Replacement>();
        }
    
        public int Bag_Code { get; set; }
        public string Bag_Dimensions { get; set; }
        public string Bag_Description { get; set; }
        public int Material_Code { get; set; }
        public int Supplier_Code { get; set; }
        public decimal Bag_Cost { get; set; }
        public int Fiber_Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bag_Replacement> Bag_Replacement { get; set; }
        public virtual Bag_Suppliers Bag_Suppliers { get; set; }
        public virtual Fiber_Brand Fiber_Brand { get; set; }
        public virtual Material_Types Material_Types { get; set; }
    }
}
