//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cooler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bag_Suppliers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bag_Suppliers()
        {
            this.Bag_Types = new HashSet<Bag_Types>();
        }
    
        public int Supplier_Code { get; set; }
        public string Supplier_Name { get; set; }
        public string Contact_Person { get; set; }
        public string Email_Address { get; set; }
        public string Telephone_Number { get; set; }
        public string Color { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bag_Types> Bag_Types { get; set; }
        public virtual Colors Color1 { get; set; }
    }
}
