//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cooler.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class database : DbContext
    {
        public database()
            : base("name=database")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bag_Replacement> Bag_Replacement { get; set; }
        public virtual DbSet<Bag_Suppliers> Bag_Suppliers { get; set; }
        public virtual DbSet<Bag_Types> Bag_Types { get; set; }
        public virtual DbSet<Cages_Maintenance> Cages_Maintenance { get; set; }
        public virtual DbSet<Compartment> Compartments { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Fiber_Brand> Fiber_Brand { get; set; }
        public virtual DbSet<Filter> Filters { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<Material_Types> Material_Types { get; set; }
        public virtual DbSet<Moveable_Beams> Moveable_Beams { get; set; }
        public virtual DbSet<Nozle_Spares> Nozle_Spares { get; set; }
        public virtual DbSet<Nozle_Types> Nozle_Types { get; set; }
        public virtual DbSet<Replacement_Reasons> Replacement_Reasons { get; set; }
        public virtual DbSet<Replacement> Replacements { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Valves_Maintenance> Valves_Maintenance { get; set; }
        public virtual DbSet<Vibrator> Vibrators { get; set; }
        public virtual DbSet<Colors> Colors { get; set; }
        public virtual DbSet<Nozle_Colors> Nozle_Colors { get; set; }
        public virtual DbSet<Nozle_Suppliers> Nozle_Suppliers { get; set; }
    }
}
