//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cooler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filter()
        {
            this.Bag_Replacement = new HashSet<Bag_Replacement>();
            this.Cages_Maintenance = new HashSet<Cages_Maintenance>();
            this.Valves_Maintenance = new HashSet<Valves_Maintenance>();
            this.Vibrators = new HashSet<Vibrator>();
        }
    
        public string Filter_Code { get; set; }
        public string Filter_Description { get; set; }
        public string Department_Code { get; set; }
        public int Manufacturer_Code { get; set; }
        public int No_Of_Sectors { get; set; }
        public int Sector_No_Valves { get; set; }
        public int Bags_Per_Valve { get; set; }
        public int No_Of_Vibrators { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bag_Replacement> Bag_Replacement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cages_Maintenance> Cages_Maintenance { get; set; }
        public virtual Department Department { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Valves_Maintenance> Valves_Maintenance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vibrator> Vibrators { get; set; }
    }
}
