//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cooler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moveable_Beams
    {
        public int Compartment_ID { get; set; }
        public int Beam_no { get; set; }
        public bool Moveable { get; set; }
    
        public virtual Compartment Compartment { get; set; }
    }
}
