//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cooler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nozle_Colors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nozle_Colors()
        {
            this.Nozle_Suppliers = new HashSet<Nozle_Suppliers>();
        }
    
        public string Color { get; set; }
        public bool Available { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nozle_Suppliers> Nozle_Suppliers { get; set; }
    }
}
