//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cooler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nozle_Spares
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nozle_Spares()
        {
            this.Replacements = new HashSet<Replacement>();
        }
    
        public int Spare_ID { get; set; }
        public int Nozle_ID { get; set; }
        public int Spare_Store_Id { get; set; }
        public string Description { get; set; }
        public string Supplier { get; set; }
        public decimal Cost { get; set; }
        public int Supplier_ID { get; set; }
    
        public virtual Nozle_Types Nozle_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Replacement> Replacements { get; set; }
        public virtual Nozle_Suppliers Nozle_Suppliers { get; set; }
    }
}
