//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cooler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Replacement
    {
        public int Replacement_ID { get; set; }
        public int Beam_no { get; set; }
        public int Nozle_no { get; set; }
        public int Spare_ID { get; set; }
        public int Compartment_ID { get; set; }
        public int Nozle_ID { get; set; }
        public System.DateTime Date { get; set; }
        public int Replacement_Reason_Code { get; set; }
        public System.DateTime Create_Date { get; set; }
    
        public virtual Compartment Compartment { get; set; }
        public virtual Nozle_Spares Nozle_Spares { get; set; }
        public virtual Nozle_Types Nozle_Types { get; set; }
        public virtual Replacement_Reasons Replacement_Reasons { get; set; }
    }
}
